import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("Cuisines.csv")
delivery_counts = df['Has Online delivery'].value_counts()
booking_counts = df['Has Table booking'].value_counts()
print("Online Delivery:\n",delivery_counts)
print("Table Delivery:\n",booking_counts)
plt.figure()
plt.bar(delivery_counts.index.astype(str),delivery_counts.values)
plt.xlabel("Online Delivery")
plt.ylabel("Number of Restaurants")
plt.title("Online Delivery Available")
plt.show()
plt.figure()
plt.bar(booking_counts.index.astype(str),booking_counts.values)
plt.xlabel("Table booking")
plt.ylabel("Number of Restaurants")
plt.title("Table booking  Available")
plt.show()